// GAVEL English Change Log — content sections 1–5
// All facts sourced from worklog.md (Tasks 1–10), git history, and verified session records.

const sections = [
  {
    h1: "1. Executive Summary",
    blocks: [
      { p: "This document is the complete English-language record of every change made to the GAVEL project during the September 2026 working engagement. It consolidates ten tracked work tasks, the full git history of twenty-five commits, and all supporting deliverables into one narrative, translated and expanded from the working log kept throughout the engagement. Each section states what was requested, what was changed, how the change was verified, and what remains open, so that the record can be read end to end without any other context." },
      { p: "The headline outcomes are as follows. The application was fully rebranded from ShipLedger to GAVEL across 127 references in 29 files, covering code paths, the session cookie, request headers, and environment variables. Security posture was raised with login rate limiting, cross-site request forgery closure, and a zero-placeholder policy under which every figure shown on screen is backed by live database data. Repository authorship was corrected so that every commit is authored by VampFay and the history was pushed to github.com/VampFay/GAVEL with a green continuous integration run." },
      { p: "Product quality work delivered a release-readiness audit that fixed a suppression defect in the extraction engine, a sixteen-behavior motion system built with zero new dependencies, a three-layer verification record, and a portable release package of twenty-five files. The verification record is worth stating precisely: the static suite passed 144 of 144 tests with zero ESLint errors and a green production build, and live browser-driven QA passed 21 of 21 assertions with zero page or console errors. Separately, two sandbox outages were root-caused and closed with structural fixes, leaving the preview live end to end and the server lifecycle fully covered by documented runbook scripts." },
      { p: "Two actions remain open: pushing the newest commits to GitHub under a fresh personal access token, and executing the phased hardening roadmap (Phases A through F) synthesized from the architecture audit. Section 11 lists the pending actions in full, and section 9 maps every task to its commit." },
    ],
  },
  {
    h1: "2. Project Context and Engagement Scope",
    blocks: [
      { p: "GAVEL is an audit and verdict workbench built on Next.js 16 with the App Router, written in TypeScript and executed on the Bun runtime. Data access goes through Prisma over SQLite, the interface is built with Tailwind CSS 4 and shadcn/ui components, and client state is managed with Zustand. The domain model follows a case-file metaphor: clients, findings, evidence chips, verdicts, audit trails, and monitoring. That metaphor is why the motion vocabulary introduced later in the engagement speaks in terms of paper, ink, and stamps rather than generic web animations." },
      { p: "The repository carries earlier development phases below the engagement's first commit: the initial scaffold, a realness sweep that fixed nineteen defects found by a full UI and API audit, hardening of the fresh-clone bootstrap, removal of sandbox infrastructure from git tracking, a UI-UX case-file workbench redesign, a human-layer pass with verdict stamps and paper grain, and a full live re-run that removed the last scaffold route and established a 78-assertion live audit harness. The tracked engagement described in this document begins after those phases, with the rename to GAVEL." },
      { p: "The engagement was executed under a strict working protocol. Every task received an extremely detailed todo plan with identifiers, dependencies, and acceptance criteria before any code was written, and no context was allowed to drift between tasks. All work was recorded in a shared append-only worklog (worklog.md) with one section per task; that worklog is the factual basis of this document. Verification was never optional: each task closed with the full static suite, and wherever the change touched user-visible behavior, with live browser-driven QA against a running server." },
      { p: "The working environment is a sandboxed Linux container, and its topology matters to several sections of this record. A Caddy gateway owned by root listens on port 81 and proxies to the application dev server on port 3000, and the preview panel goes through that gateway. Processes started by the user account inside a tool call are reaped when the call ends, while processes in the platform's own tree survive. This asymmetry became the central fact of the sandbox operations described in section 7." },
    ],
  },
  {
    h1: "3. Brand Migration and Repository Ownership",
    blocks: [
      { h2: "3.1 Full Rename: ShipLedger to GAVEL" },
      { p: "The first task renamed the product end to end, from ShipLedger to GAVEL. The sweep covered 127 references across 29 files. The component directory src/components/shipledger/ became src/components/gavel/, the library module became lib/gavel.ts, and every import path was updated to match the new names." },
      { p: "The rename deliberately extended to the runtime contract, which makes it a breaking change for deployments. The session cookie became gavel_token, the custom request headers became x-gavel-*, and every environment variable moved from the SHIPLEDGER_ prefix to the GAVEL_ prefix. Operators upgrading across this boundary must update their environment before redeploying, and that requirement is recorded in the README rather than left to be discovered." },
      { p: "The change was committed and verified with the full test suite, which passed 141 of 141 assertions at that point in the engagement. No behavioral change was intended or observed; the rename is purely lexical, which is exactly what the green suite confirms. The current hash for this commit is f55bea8; as explained in section 9, the commit was rehashed twice by later history maintenance (the author rewrite in section 3.3 and the rebase cleanup in section 7.1), with the file trees verified byte-identical each time." },
      { h2: "3.2 Brand Assets and Security Hardening" },
      { p: "The second task replaced placeholder-grade branding and hardened the application against abuse. New brand assets were produced: an SVG gavel logo, a favicon, and an Open Graph card, together with a render-og script that generates the card deterministically. The script was later adjusted to run as an ES module with node-style imports and a dirname shim, removing the last require() call (commit 6dd9648)." },
      { p: "On the security side, the login endpoint gained two independent rate limits: ten attempts per five minutes per IP address, and ten attempts per fifteen minutes per email address, so that both credential stuffing from one source and targeted guessing against one account are throttled. A residual cross-site request forgery exposure was closed. The README was rewritten to document the security posture explicitly, covering quickstart, environment variables, and verification status." },
      { p: "The task also enforced a zero-placeholder bar, referred to internally as the real-money bar: the landing page renders only live data pulled from the database, and no UI element ships fake numbers, dummy sections, or decorative dead links. Everything a visitor sees is backed by real rows. The work landed as commit c527c45 with the suite again green at 141 of 141." },
      { h2: "3.3 GitHub Push Under the Owner's Identity" },
      { p: "The third task made the GitHub repository genuinely the owner's. The project had accumulated eighteen commits whose recorded authorship did not reflect the owner, so every commit author was rewritten to VampFay using git filter-branch. Before pushing, each rewritten tree was verified byte-identical to its original, guaranteeing that only metadata changed and never content. The rewritten history was force-pushed, and the GitHub Actions run came back green (run 34339722387)." },
      { p: "Local and repository git identity was pinned to the owner's noreply address so that all future commits inherit correct authorship automatically. A one-shot push script, scripts/push-github.sh, was added with a strict security design: the token is accepted only through the GAVEL_GH_TOKEN environment variable and never on the command line or in files; authentication uses the x-access-token form so that no interactive prompt is possible; force-push requires an explicit FORCE=1 opt-in; and the script verifies the remote SHAs after pushing. Two follow-up fixes refined the script, correcting the FORCE mode flag handling (ce2bd89) and the non-interactive auth form (9b62f0d)." },
      { p: "One security consequence is recorded here for the file: the personal access token used during this task traveled through chat, so it must be treated as exposed and revoked. Future pushes require a fresh token with Contents read/write, Workflows read/write, and Metadata read-only scopes, passed as GAVEL_GH_TOKEN to the push script." },
    ],
  },
  {
    h1: "4. Release-Readiness Audit",
    blocks: [
      { p: "Task four was a final release-readiness pass that combined a full verification suite with a systematic source review. The suite ran ESLint with zero errors, the TypeScript compiler clean, the vitest suite at 144 of 144 assertions, and a production build against an in-memory SQLite database. The test count rose from 141 to 144 because the review added regression coverage for the defect it fixed." },
      { p: "The source review found and fixed a defect in the extraction engine's CO-suppression logic; the regression tests covering that fix account for the three new assertions. Dead dependencies that had accumulated in the package manifests were pruned. Documentation drift, meaning places where the README or code comments no longer matched actual behavior, was closed so that the shipped documents and the shipped code agree." },
      { p: "The review also documented, rather than hid, the engine's known limitation: matching relies on keyword overlap rather than semantic understanding, which bounds the extraction quality in ways operators should know about. The pass landed as commit 0f8e592 and left the repository in a state where every layer of verification was simultaneously green. That state became the baseline which every later task in the engagement was required to preserve." },
    ],
  },
  {
    h1: "5. Motion System v2: The Case File Comes Alive",
    blocks: [
      { p: "Task five was a design-and-build effort: motion system version 2, under the creative brief that the case file comes alive. The constraint set was deliberately strict. Sixteen new motion behaviors were designed inside the existing paper, ink, and stamp forensic vocabulary; no new dependencies were added; and every behavior had to respect the reduced-motion accessibility guard so that users who opt out of animation still receive a fully usable, static-but-dignified interface." },
      { h2: "5.1 Design Language and Foundation" },
      { p: "The foundation lives in globals.css, which gained twelve keyframe and utility families: page-forward and page-backward turns, drawer in and out, verdict-pulse, table-thud, ink-fill-x, seg-pop, paper-drift, shimmer-sweep, timeline-draw, tabs-ink, logo-strike, chip-press, arrow-nudge, breathe-fast, skeleton-ink, stamp-xl, and the view-transition pins. The reduced-motion guard was extended so that each of these degrades to an acceptable static state rather than simply being removed." },
      { p: "Three new modules consume the vocabulary. The hook use-in-view drives one-shot reveal animations through an IntersectionObserver, so content animates exactly once when it enters the viewport. The Reveal and RevealLine components wrap content for staggered entrances and line-by-line ink reveals. The VerdictFlash component delivers the signature moment, a stamp slam with an ink splat and a table thud, triggered whenever a ruling is issued." },
      { p: "State support was added to the Zustand store: navDir tracks the binder navigation order so that page turns can be directional (forward when descending the binder, backward when ascending), and verdictFlash plus its trigger action drive the flash lifecycle from anywhere in the component tree. No API or database schema was touched by this task, and the dependency count did not change." },
      { h2: "5.2 Application Across Surfaces" },
      { p: "The app shell received the structural moves. Main content performs a directional page turn based on navigation order; the mobile drawer slides and fades with a choreographed close sequence; the VerdictFlash overlay is mounted at the shell level so that the whole workbench receives the thud; and the theme toggle now flips between light and dark through the View Transitions API with an ink-drop circle reveal, resolving instantly under reduced-motion. Each surface then received its own choreography:" },
      { bullets: [
        "Landing: hero paper-drift, seventeen reveal wrappers, a RevealLine chain rule, staggered metrics, price-tile lift with a breathing highlight, and arrow nudges.",
        "Review queue: verdict flash on approve, dismiss, and escalate; a tabs-ink underline; confidence-meter sliver pop; and evidence-chip press feedback.",
        "Finding detail: staggered ink-fill confidence bars, an anim-timeline spine draw, flash triggers, and skeleton shimmer.",
        "Audits: a four-segment status bar that fills in verdict order with per-segment delays.",
        "Monitoring: a critical heartbeat that breathes at twice the normal rate.",
        "Dashboard and chrome: audit-log riffle, shimmer skeletons, loading-state shimmer, a noscript reveal fallback, and a logo hover strike.",
      ] },
      { h2: "5.3 Live Verification" },
      { p: "Every behavior was verified live in a real browser, not only by code review. Scroll reveals were observed firing in order as the page was scrolled; the verdict flash DOM lifecycle was measured precisely, with the overlay lasting about 1.1 seconds and the thud 380 milliseconds; the drawer's entering and exiting classes were inspected through mount and clean unmount; the tabs-ink underline was confirmed to render; three Approved stamps, four plus four ink-fill bars, the breathe-fast state on a critical row, and the theme flip through startViewTransition were all directly observed. Zero page errors and zero console errors were recorded across the whole pass." },
      { p: "The static suite confirmed the discipline held: ESLint reported zero errors, type checking was clean, the test suite passed 144 of 144, and the production build was green. Stray executable file modes that had crept into the tree were restored to 644 before committing, keeping the repository's file permissions clean. The work landed as commit 107c584, and QA screenshots from this and the following task are preserved under the download directory." },
    ],
  },
];

module.exports = { sections };
