// GAVEL — provider-aware `prisma generate` wrapper.
//
// The generated Prisma client is bound to the provider of the schema file
// it was generated from. Dev/test use SQLite (prisma/schema.prisma);
// production uses PostgreSQL (prisma/schema.postgres.prisma, generated by
// scripts/sync-pg-schema.ts). This script picks the right one from the
// DATABASE_URL protocol so `postinstall` works in every environment:
//
//   postgres://… or postgresql://…  → schema.postgres.prisma
//   file:… (or unset)              → schema.prisma (sqlite)
//
// Production images therefore just set DATABASE_URL before `bun install`
// and get a PG-bound client; the dev sandbox keeps its SQLite client with
// zero configuration.

import { spawnSync } from 'node:child_process'
import { existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const ROOT = join(here, '..')

const url = process.env.DATABASE_URL ?? ''
const wantsPostgres = url.startsWith('postgres://') || url.startsWith('postgresql://')

const schema = wantsPostgres
  ? join(ROOT, 'prisma', 'schema.postgres.prisma')
  : join(ROOT, 'prisma', 'schema.prisma')

if (wantsPostgres && !existsSync(schema)) {
  console.error(
    '❌ DATABASE_URL points at Postgres but prisma/schema.postgres.prisma is missing.\n' +
    '   Run `bun scripts/sync-pg-schema.ts` first.'
  )
  process.exit(1)
}

console.log(`prisma generate → ${schema} (${wantsPostgres ? 'postgresql' : 'sqlite'})`)

const result = spawnSync('bunx', ['prisma', 'generate', '--schema', schema], {
  stdio: 'inherit',
  cwd: ROOT,
})

process.exit(result.status ?? 1)
